security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
              users: 
                "%admin_username%": { password: "%admin_password%" }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        loginarea:
          pattern: ^/login$
          anonymous: ~
        secured:
          pattern: ^/
          form_login:
              csrf_provider: form.csrf_provider
          logout:       true
          form_login:
            check_path: /login_check
            login_path: /login
            target: /entry/
          logout:
            path: /logout
            target: /
