<?php

namespace Gehaxelt\SyMDWikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{

  public function getLastModified($limit) {
    $query = $this->getEntityManager()
                  ->createQuery("SELECT e FROM GehaxeltSyMDWikiBundle:Entry e 
                                ORDER BY e.lastmodified DESC")
                  ->setMaxResults($limit);

    return  $query->getResult();
  }
}
