<?php

namespace Gehaxelt\SyMDWikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
  /**
   * Deletes all logentries
  **/
  public function deleteAll() {
    $query = $this->getEntityManager()->createQuery("DELETE from GehaxeltSyMDWikiBundle:Log");
    return $query->execute();
  }

  /**
  * Gets the amount of log entries
  * @return integer - Count of log entries 
  */
  public function getLogCount() {
    $query = $this->getEntityManager()->createQuery("SELECT COUNT(m) FROM GehaxeltSyMDWikiBundle:Log m");

    return  (int) $query->getScalarResult()[0][1];

  }

}
